development:
  adapter: postgresql
  encoding: unicode
  database: next_voting_app_db
  pool: 5
  username:
  password:
  timeout: 5000

# production setup is not required for Heroku

test:
  adapter: postgresql
  encoding: unicode
  database: next_voting_app_db
  pool: 5
  username:
  password:
  timeout: 5000