# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18c3a1d77e0612168c23a04c9cdd7d000a44aa8e8bcd177b42b28ac395129c9d794fbea53d34b926d5154bd9a67ce007dc614a185c4801eb18ba94cef10ddd7b

test:
  secret_key_base: efce57057bc2b425d8203d47fcaaf70caa7382789a5816db442558328257f5a22623e62ed775fece6f9f588f089cd1019bda5fa86d5aff3024aebba743168948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
